
export enum DeviceStatus { 
  OPERATIONAL = 0,
  OPERATIONAL_READ_ONLY = 1,
  DOWNLOAD_REQUIRED = 2,
  DOWNLOAD_IN_PROGRESS = 3,
  NON_OPERATIONAL = 4,
  BACKUP_IN_PROGRESS = 5,
}

export enum Segmentation {
  SEGMENTED_BOTH = 0,
  SEGMENTED_TRANSMIT = 1,
  SEGMENTED_RECEIVE = 2,
  NO_SEGMENTATION = 3,
}
