
import { BitString } from './bitstring.js'; 

export enum SupportedServicesBit {
  ACKNOWLEDGE_ALARM = 0,
  CONFIRMED_COV_NOTIFICATION = 1,
  CONFIRMED_EVENT_NOTIFICATION = 2,
  GET_ALARM_SUMMARY = 3,
  GET_ENROLLMENT_SUMMARY = 4,
  SUBSCRIBE_COV = 5,
  ATOMIC_READ_FILE = 6,
  ATOMIC_WRITE_FILE = 7,
  ADD_LIST_ELEMENT = 8,
  REMOVE_LIST_ELEMENT = 9,
  CREATE_OBJECT = 10,
  DELETE_OBJECT = 11,
  READ_PROPERTY = 12,
  READ_PROPERTY_MULTIPLE = 14,
  WRITE_PROPERTY = 15,
  WRITE_PROPERTY_MULTIPLE = 16,
  DEVICE_COMMUNICATION_CONTROL = 17,
  CONFIRMED_PRIVATE_TRANSFER = 18,
  CONFIRMED_TEXT_MESSAGE = 19,
  REINITIALIZE_DEVICE = 20,
  VT_OPEN = 21,
  VT_CLOSE = 22,
  VT_DATA = 23,
  READ_PROPERTY_CONDITIONAL = 13,
  AUTHENTICATE = 24,
  REQUEST_KEY = 25,
  I_AM = 26,
  I_HAVE = 27,
  UNCONFIRMED_COV_NOTIFICATION = 28,
  UNCONFIRMED_EVENT_NOTIFICATION = 29,
  UNCONFIRMED_PRIVATE_TRANSFER = 30,
  UNCONFIRMED_TEXT_MESSAGE = 31,
  TIME_SYNCHRONIZATION = 32,
  WHO_HAS = 33,
  WHO_IS = 34,
  READ_RANGE = 35,
  UTC_TIME_SYNCHRONIZATION = 36,
  LIFE_SAFETY_OPERATION = 37,
  SUBSCRIBE_COV_PROPERTY = 38,
  GET_EVENT_INFORMATION = 39,
  WRITE_GROUP = 40,
  SUBSCRIBE_COV_PROPERTY_MULTIPLE = 41,
  CONFIRMED_COV_NOTIFICATION_MULTIPLE = 42,
  UNCONFIRMED_COV_NOTIFICATION_MULTIPLE = 43,
}

export class SupportedServicesBitString extends BitString<typeof SupportedServicesBit> {
  constructor(...trueBits: SupportedServicesBit[]) { 
    super(112, trueBits);
  }
}

